Siscom/Siscom/Areas/Global/Controllers/CuentaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Siscom.Controllers;
using Siscom.Entity.Global;
using Siscom.Models;
using Siscom.SClient.Global;
using Siscom.WebLib.MvcShared;
using Siscom.Utility;
using Siscom.Controllers.Base;
using Siscom.Areas.Global.Models;
using Siscom.Areas.Global.Models.Validator;
using Siscom.Entity.Persona;
using Elmah;
using Procedimiento.A_Seleccion;
using Entidad.A_Seleccion;

namespace Siscom.Areas.Global.Controllers
{
    public class CuentaController : BaseModelController<CuentaModels>
    {
        CuentaRestClient oCuentaRestClient;


       public CuentaController()
            :base(new CuentaModelsValidator())
        {
            oCuentaRestClient = new CuentaRestClient();
        }

        public ActionResult Index()
        {
            if (UsuarioSession.Usuario1.nu_id_cuenta == null)
            {
                return RedirectToAction("Login", "Login");
            }
            /*open>>> Información: Código de identificación estándar */
            Decimal? Idns = 10001;
            /*close>> Información */

            try
            {
                var CuentaObj = new CuentaModels();

                var model = new CuentaModels();
            
                return View(model);
            }
            catch (Exception Ex)
            {
                ErrorSignal.FromCurrentContext().Raise(Ex); //ELMAH Signaling
                throw;
            }

        }

        public ActionResult Guardar(CuentaModels Model)
        {
            /*open>>> Información: Código de identificación estándar */
            Decimal? Idns = 10002;
            /*close>> Información */

            try
            {
                var Cuenta = new CuentaBE();
                Cuenta = Model.Cuenta;
                Cuenta.vc_usr_reg = UsuarioSession.Usuario1.vc_cod_usuario;
                Cuenta.ch_status = "A";
                string fechacierre;
                fechacierre = DateTime.Now.ToShortDateString();
                Cuenta.dt_fec_reg = Convert.ToDateTime(fechacierre);
                Cuenta.nu_id_perfil = 1;
                Cuenta.opcion = 0;
                Cuenta = oCuentaRestClient.Save(Cuenta);
                return AjaxResultSuccess("go");
            }
            catch (Exception ex)
            {
                ErrorSignal.FromCurrentContext().Raise(ex); //ELMAH Signaling
                return AjaxResultSuccess(ex.Message.Split('\"')[7].Split('\\')[0]);
            }
        }

        public ActionResult Bandeja()
        {
            /*open>>> Información: Código de identificación estándar */
            Decimal? Idns = 10003;
            /*close>> Información */
            if (UsuarioSession.Usuario1.nu_id_cuenta == null)
            {
                return RedirectToAction("Login", "Login");
            }
            try
            {
                var Cuenta = new CuentaBE();
                var ListaCuenta = new List<CuentaBE>();

                var model = new CuentaModels();
                Cuenta.nu_id_cuenta = UsuarioSession.Usuario1.nu_id_cuenta;

                //if (Cuenta.nu_id_cuenta != 1)
                //{
                //    Cuenta.nu_id_cuenta = null;
                //}
                model.ListaCuenta = oCuentaRestClient.GetByFilters(Cuenta);

                return View(model);
            }
            catch (Exception ex)
            {
                ErrorSignal.FromCurrentContext().Raise(ex); //ELMAH Signaling
                throw;
            }


        }


        public ActionResult Buscar()
        {
            /*open>>> Información: Código de identificación estándar */
            Decimal? Idns = 10004;
            /*close>> Información */

            try
            {
                var Cuenta = new CuentaBE();
                var ListaCuenta = new List<CuentaBE>();

                var model = new CuentaModels();
                Cuenta.nu_id_cuenta = UsuarioSession.Usuario1.nu_id_cuenta;

                //if (Cuenta.nu_id_cuenta != 1)
                //{
                //    Cuenta.nu_id_cuenta = null;
                //}
                model.ListaCuenta = oCuentaRestClient.GetByFilters(Cuenta);

                if (Request.IsAjaxRequest())
                {
                    return PartialView("VP_GrillaCuenta", model);
                }
                else
                {
                    return View(model);
                }
            }
            catch (Exception ex)
            {
                ErrorSignal.FromCurrentContext().Raise(ex); //ELMAH Signaling
                throw;
            }
        }

        public ActionResult Select(int idCuenta)
        {

            /*open>>> Información: Código de identificación estándar */
            Decimal? Idns = 10005;
            /*close>> Información */


            try
            {
                var model = new CuentaModels();

                /*Consultando traslado por Id*/
                model.Cuenta = oCuentaRestClient.GetById(idCuenta);

                /*Retornado la vista con el modelo seteado*/
                return View("Select", model); ;
            }
            catch (Exception ex)
            {
                ErrorSignal.FromCurrentContext().Raise(ex); //ELMAH Signaling
                return AjaxResultError(ex.Message);
            }
        }

        public ActionResult Actualizar(CuentaModels Model)
        {
            /*open>>> Información: Código de identificación estándar */
            Decimal? Idns = 10002;
            /*close>> Información */


            try
            {
                var Cuenta = new CuentaBE();
                Cuenta = Model.Cuenta;
                Cuenta.vc_usr_mod = UsuarioSession.Usuario1.vc_cod_usuario;
                string fechacierre;
                fechacierre = DateTime.Now.ToShortDateString();
                Cuenta.dt_fec_mod = Convert.ToDateTime(fechacierre);
                Cuenta.opcion = 1;

                Cuenta = oCuentaRestClient.Save(Cuenta);
                return AjaxResultSuccess("go");
            }
            catch (Exception ex)
            {
                ErrorSignal.FromCurrentContext().Raise(ex); //ELMAH Signaling
                return AjaxResultSuccess(ex.Message.Split('\"')[7].Split('\\')[0]);
            }
        }

        public ActionResult Ficha()
        {

            /*open>>> Información: Código de identificación estándar */
            Decimal? Idns = 10005;
            /*close>> Información */


            try
            {
                var model = new CuentaModels();

                /*Consultando traslado por Id*/
                int idCuenta;
                idCuenta = Convert.ToInt32(UsuarioSession.Usuario1.nu_id_cuenta);
                model.Cuenta = oCuentaRestClient.GetById(idCuenta);

                /*Retornado la vista con el modelo seteado*/
                return View("Ficha", model); ;
            }
            catch (Exception ex)
            {
                ErrorSignal.FromCurrentContext().Raise(ex); //ELMAH Signaling
                return AjaxResultError(ex.Message);
            }
        }

        public ActionResult ChangePassword()
        {
            if (UsuarioSession.Usuario1.nu_id_cuenta == null)
            {
                return RedirectToAction("Login", "Login");
            }
            return View();
        }

        public ActionResult Cambiar(E_Candidato_Evaluacion pCuenta)
        {
            try
            {
                P_Candidato_Evaluacion obj = new P_Candidato_Evaluacion();
               pCuenta.vc_cod_usuario = UsuarioSession.Usuario1.vc_cod_usuario;

                string hoy;
                hoy = DateTime.Now.ToShortDateString();
                E_Candidato_Evaluacion output = new E_Candidato_Evaluacion();
                output = obj.ChangePassword(pCuenta);
                return AjaxResultSuccess(output.vc_Mensaje_Out);
            }
            catch (Exception Ex)
            {
                ErrorSignal.FromCurrentContext().Raise(Ex); //ELMAH Signaling
                return AjaxResultError(Ex.Message);
            }
        }
    }
}

Siscom/Siscom/Areas/Global/Views/Cuenta/Bandeja.cshtml
@using Siscom.Models

@model Siscom.Areas.Global.Models.CuentaModels

@{
    ViewBag.Title = "Bandeja";
    Layout = "~/Views/Home/Principal.cshtml";
}

<div class="pageheader">
    <!--Region Cabecera de la Pagina-->
    <h1>Bandeja de Cuentas</h1>
    <div>
        <span class="label" style="color:rgb(144, 157, 163);padding:0px">USTED ESTÁ AQUÍ: </span>
        <ol class="breadcrumb">
            <li>
                <a href="#">Cuentas</a>
            </li>
            <li>
                <a href="../../Global/Cuenta/Bandeja" class="active">Bandeja</a>
            </li>
        </ol>
    </div>
</div>


<section id="main-content" class="animated fadeInUp">
<!--Region Botones-->
    <div class="row">
        <div class="col-xs-12">
           <div class="panel panel-default">                          
                <div class="panel-body text-left">
                    <button id="buscarBtn" type="button" class="btn btn-search btn-sm"
                        onclick="Buscar();">
                        <i class="fa fa-search"></i> Buscar
                    </button>  
                    <button id="agregarBtn" type="button" class="btn btn-primary btn-sm" 
                        onclick="Create('@Url.Action("Index", "Cuenta")');">
                        <i class="fa fa-plus"></i> Nueva Cuenta
                    </button>                      
                </div>
            </div>
        </div>
    </div>

<div id="DatosForm">
  <!--Region Panel (Filtros)-->
        <div class="row">
            <div class="col-md-12">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h3 class="panel-title">Lista de cuentas</h3>
                        <div class="actions pull-right">
                            <i class="fa fa-chevron-down"></i>
                        </div>
                    </div>
<!--Lista de Usuarios-->
    <div class="row">
        <div class="col-md-12">
            <div class="panel panel-default">
                <div class="panel-body data-toggle="collapse">
                    <div id="div_ListaSolicitudes" class="table-responsive" style="padding-top:1px">
                     @Html.Partial("VP_GrillaCuenta", Model)
                    </div>
                </div>
            </div>
        </div>
    </div>
                </div>
            </div>
        </div>
</div>
 
</section>

<!--Modal para mensajes-->
<div class="modal fade" id="ModalSave" style="overflow: scroll;" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h3 class="modal-title" id="myModalLabel" style="color:#0D588E">Mensaje de busqueda de Cuenta</h3>
            </div>
            <div class="modal-body" id="SaveMensaje">
            </div>
            <div class="text-center">
                <hr /><button id="btnMensaje" type="button" class="btn btn-primary" onclick="$('#ModalSave').modal('hide');">Aceptar</button>
            </div>
        </div>
    </div>
</div>
<!--FIN-->

@section Styles {
@Styles.Render("~/plugins/dataTablesCSS")
}

<!--Load these page level functions-->
@section Scripts {
    @Scripts.Render("~/plugins/dataTables")
    @Scripts.Render("~/plugins/dataTables-bootstrap")
    @Scripts.Render("~/plugins/maskedinput")


    <script type="text/javascript" src="~/Scripts/plugins/datetimepicker/bootstrap-datetimepicker.js" charset="UTF-8"></script>
    <script type="text/javascript" src="~/Scripts/plugins/datetimepicker/locales/bootstrap-datetimepicker.es.js" charset="UTF-8"></script>
    <link href="~/Content/bootstrap-datetimepicker.min.css" rel="stylesheet" />

    <script type="text/javascript" src="~/Scripts/plugins/blockUI/js/jquery.blockUI.js" charset="UTF-8"></script>
    <script src="~/Scripts/jquery.number.js"></script>
    <script src="~/Scripts/jquery.number.min.js"></script>

<script type="text/javascript">  
    $(document).ready(function () {
        $('#DetalleSolicitudTable').dataTable({
            "order": [[3, "desc"]]
        });
        Buscar()
    });

    function Create(url) {
        window.location.href = url;
    }
   
    function Buscar() {
        $("#SaveMensaje").html('<i class="fa  fa-refresh" style="color:green"></i> Buscando cuenta, espere un momento...');
        $("#ModalSave").modal('show');
        
        $.ajax({
            type: 'POST',
            url: '/Global/Cuenta/Buscar',

            success: function (result) {
                $('#div_ListaSolicitudes').andSelf().unbind();
                $('#div_ListaSolicitudes').html(result);
                if (result.trim() == "") {
                    $("#SaveMensaje").html('<i class="fa fa-remove" style="color:darkred"></i> No se encontró datos.');
                    $("#ModalSave").modal('show');
                }
                $(document).ready(function () {
                    $('#DetalleSolicitudTable').dataTable({
                        "order": [[3, "desc"]]
                    });
                });
                $("#ModalSave").modal('hide');
            }
        });

    }
    /*Ver Usuarios*/
    function Select(idCuenta) {
        window.location.href = GetControllerUrl("Select", "Cuenta") + '?idCuenta=' + idCuenta;
    }
    /*FIN*/
</script>
}

Siscom/Siscom/Areas/Global/Views/Cuenta/VP_GrillaCuenta.cshtml
@model Siscom.Areas.Global.Models.CuentaModels


 <table id="DetalleSolicitudTable" class="table table-striped table-bordered table-hover table-condensed " cellspacing="0">
    <thead>
        <tr>
            <th class="text-center" style="vertical-align:middle"><p>ESTADO</p></th>
            <th class="text-center" hidden="hidden"><p>ID_CUENTA</p></th>
            <th class="text-center" style="vertical-align:middle"><p>CUENTA</p></th>
            <th class="text-center" style="vertical-align:middle"><p>RUC</p></th>
            <th class="text-center" style="vertical-align:middle"><p>DIRECCIÓN</p></th>
            <th class="text-center" style="vertical-align:middle"><p>DIRECCIÓN E-MAIL</p></th>
            <th class="text-center" style="vertical-align:middle"><p>TELEFONO</p></th>
            <th class="text-center" style="vertical-align:middle"><p>TIEMPO DE CONTRATO</p></th>
            <th class="text-center" style="vertical-align:middle"><p>FECHA INICIO</p></th>
            <th class="text-center" style="vertical-align:middle"><p>FECHA FINAL</p></th>
            <th class="text-center" style="vertical-align:middle"><p>D.N.I. CONTACTO</p></th>
            <th class="text-center" style="vertical-align:middle"><p>NOMBRE Y APELLIDO / CONTACTO</p></th>
            <th class="text-center" style="vertical-align:middle"><p>ACCIÓN</p></th>
        </tr>
    </thead>

    
 <tbody id="itemsDetalle">
@if (Model.ListaCuenta != null)
{
        foreach (var item in Model.ListaCuenta)
        { 
            <tr>
                <td class="text-center" style="font-weight:100; vertical-align:middle">
                @if(item.ch_status == "A")
                {
                    <button type="button" class="btn btn-primary">
                        <h2 style="color:white">A</h2>
                    </button>
                }
                
                @if(item.ch_status == "I")
                {
                    <button type="button" class="btn btn-danger">
                        <h2 style="color:white">I</h2>
                    </button>
                }</td>

                <td hidden="hidden" ><p>@(item.nu_id_cuenta)</p></td>
                <td class="text-center" style="vertical-align:middle"><p>@(item.vc_desc_cuenta)</p></td>
                <td class="text-center" style="vertical-align:middle"><p>@(item.vc_ruc)</p></td>
                <td class="text-center" style="vertical-align:middle"><p>@(item.vc_direccion)</p></td>
                <td class="text-center" style="vertical-align:middle"><p>@(item.vc_direccion_email)</p></td>
                <td class="text-center" style="vertical-align:middle"><p>@(item.vc_telefono)</p></td>
                <td class="text-center" style="vertical-align:middle"><p>@(item.nu_tiempo_duracion)</p></td>
                <td class="text-center" style="vertical-align:middle"><p>@item.dt_fecha_inicio.Value.ToString("yyyy/MM/dd")</p></td>
                <td class="text-center" style="vertical-align:middle"><p>@item.dt_fecha_fin.Value.ToString("yyyy/MM/dd")</p></td>
                <td class="text-center" style="vertical-align:middle"><p>@(item.vc_doc_identi)</p></td>
                <td class="text-center" style="vertical-align:middle"><p>@(item.vc_nombres+' '+item.vc_apellidos)</p></td>
                <td class="text-center" style="vertical-align:middle"><button id="Ver" type="button" class="btn btn-info" onclick="Select(@item.nu_id_cuenta);">
                    <i class="fa fa-search"></i>
                </button>
                </td>
            </tr>
        }
}                                        
    </tbody>
 </table>
      
    