Siscom/Siscom/Areas/Global/Controllers/SubCuentasController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Siscom.Controllers;
using Siscom.Entity.Global;
using Siscom.Models;
using Siscom.SClient.Global;
using Siscom.WebLib.MvcShared;
using Siscom.Utility;
using Siscom.Controllers.Base;
using Siscom.Areas.Global.Models;
using Siscom.Areas.Global.Models.Validator;
using Siscom.Entity.Persona;

using Elmah;

namespace Siscom.Areas.Global.Controllers
{
    public class SubCuentasController : BaseModelController<SubCuentasModels>
    {
        SubCuentaRestClient oSubCuentaRestClient;

        public SubCuentasController()
            :base(new SubCuentasModelsValidator())
        {
            oSubCuentaRestClient = new SubCuentaRestClient();
        }
        
        public ActionResult Index()
        {
            /*open>>> Información: Código de identificación estándar */
                      Decimal? Idns = 20001;
            /*close>> Información */
            if (UsuarioSession.Usuario1.nu_id_cuenta == null)
            {
                return RedirectToAction("Login", "Login");
            }
            try
            {
                var SubCuentaObj = new SubCuentasModels();

                var model = new SubCuentasModels();
                if (UsuarioSession.Usuario1.nu_id_perfil > 1)
                {
                    SubCuentaObj.Persona.vc_criterio = UsuarioSession.Usuario1.vc_desc_cuenta;
                }
                else
                {
                    SubCuentaObj.Persona.vc_criterio = "";
                }
                SubCuentaObj.Persona.ch_status = "A";
                model.SubCuenta.vc_desc_cuenta = UsuarioSession.Usuario1.vc_desc_cuenta;

                return View(model);
            }
            catch (Exception ex)
            {
                ErrorSignal.FromCurrentContext().Raise(ex); //ELMAH Signaling          
                throw;
            }

        }

        public ActionResult Guardar(SubCuentasModels Model)
        {
            /*open>>> Información: Código de identificación estándar */
            Decimal? Idns = 20002;
            /*close>> Información */


            try
            {
                var SubCuenta = new SubCuentaBE();
                SubCuenta = Model.SubCuenta;
                SubCuenta.vc_usr_reg = UsuarioSession.Usuario1.vc_cod_usuario;
                SubCuenta.ch_status = "A";
                string fechacierre;
                fechacierre = DateTime.Now.ToShortDateString();
                SubCuenta.dt_fec_reg = Convert.ToDateTime(fechacierre);
                SubCuenta.nu_id_cuenta = UsuarioSession.Usuario1.nu_id_cuenta;
                SubCuenta.nu_id_perfil = 2;
                SubCuenta.opcion = 0;
                SubCuenta = oSubCuentaRestClient.Save(SubCuenta);
                return AjaxResultSuccess("go");
            }
            catch (Exception ex)
            {
                ErrorSignal.FromCurrentContext().Raise(ex); //ELMAH Signaling
                return AjaxResultSuccess(ex.Message.Split('\"')[7].Split('\\')[0]);
            }
        }

        public ActionResult Bandeja()
        {
            /*open>>> Información: Código de identificación estándar */
            Decimal? Idns = 20003;
            /*close>> Información */
            if (UsuarioSession.Usuario1.nu_id_cuenta == null)
            {
                return RedirectToAction("Login", "Login");
            }
            try
            {
                var SubCuenta = new SubCuentaBE();
                var ListaSubCuenta = new List<SubCuentaBE>();

                var model = new SubCuentasModels();


                if (UsuarioSession.Usuario1.nu_id_perfil == 2)
                {
                    SubCuenta.nu_id_cuenta = UsuarioSession.Usuario1.nu_id_cuenta;
                    SubCuenta.vc_criterio = UsuarioSession.Usuario1.vc_desc_sub_cuenta;
                }
                else
                {

                    SubCuenta.nu_id_cuenta = null;
                    SubCuenta.vc_criterio = "";
                }
                model.ListaSubCuenta = oSubCuentaRestClient.GetByFilters(SubCuenta);
            
                return View(model);
            }
            catch (Exception ex)
            {
                ErrorSignal.FromCurrentContext().Raise(ex); //ELMAH Signaling
                throw;
            }


        }

        public ActionResult Buscar()
        {
            /*open>>> Información: Código de identificación estándar */
            Decimal? Idns = 20004;
            /*close>> Información */

            try
            {
                var SubCuenta = new SubCuentaBE();
                var ListaSubCuenta = new List<SubCuentaBE>();

                var model = new SubCuentasModels();

                SubCuenta.nu_id_cuenta = UsuarioSession.Usuario1.nu_id_cuenta;

                if (UsuarioSession.Usuario1.nu_id_perfil == 2)
                {
                    SubCuenta.nu_id_cuenta = UsuarioSession.Usuario1.nu_id_cuenta;
                    SubCuenta.vc_criterio = UsuarioSession.Usuario1.vc_desc_sub_cuenta;
                }
                if (UsuarioSession.Usuario1.nu_id_perfil == 1)
                {
                    SubCuenta.nu_id_cuenta = UsuarioSession.Usuario1.nu_id_cuenta;
                    SubCuenta.vc_criterio = "";
                }
                else
                {

                    SubCuenta.nu_id_cuenta = null;
                    SubCuenta.vc_criterio = "";
                }

                model.ListaSubCuenta = oSubCuentaRestClient.GetByFilters(SubCuenta);

                if (Request.IsAjaxRequest())
                {
                    return PartialView("VP_GrillaSubCuentas", model);
                }
                else
                {
                    return View(model);
                }
            }
            catch (Exception ex)
            {
                ErrorSignal.FromCurrentContext().Raise(ex); //ELMAH Signaling
                throw;
            }


        }

        public ActionResult Select(int IdSubCuenta)
        {
            /*open>>> Información: Código de identificación estándar */
            Decimal? Idns = 20005;
            /*close>> Información */


            try
            {
                var model = new SubCuentasModels();

                /*Consultando traslado por Id*/
                model.SubCuenta = oSubCuentaRestClient.GetById(IdSubCuenta);

                /*Retornado la vista con el modelo seteado*/
                return View("Select", model); ;
            }
            catch (Exception ex)
            {
                ErrorSignal.FromCurrentContext().Raise(ex); //ELMAH Signaling
                return AjaxResultError(ex.Message);
            }
        }

        public ActionResult Ficha()
        {
            /*open>>> Información: Código de identificación estándar */
            Decimal? Idns = 20005;
            /*close>> Información */


            try
            {
                var model = new SubCuentasModels();
                int IdSubCuenta;
                IdSubCuenta = Convert.ToInt32(UsuarioSession.Usuario1.nu_id_subcuenta);
                /*Consultando traslado por Id*/
                model.SubCuenta = oSubCuentaRestClient.GetById(IdSubCuenta);

                /*Retornado la vista con el modelo seteado*/
                return View("Ficha", model); ;
            }
            catch (Exception ex)
            {
                ErrorSignal.FromCurrentContext().Raise(ex); //ELMAH Signaling
                return AjaxResultError(ex.Message);
            }
        }

        public ActionResult Actualizar(SubCuentasModels Model)
        {
            /*open>>> Información: Código de identificación estándar */
            Decimal? Idns = 10002;
            /*close>> Información */


            try
            {
                var Subcuenta = new SubCuentaBE();
                Subcuenta = Model.SubCuenta;
                Subcuenta.vc_usr_mod = UsuarioSession.Usuario1.vc_cod_usuario;
                string fechacierre;
                fechacierre = DateTime.Now.ToShortDateString();
                Subcuenta.dt_fec_mod = Convert.ToDateTime(fechacierre);
                Subcuenta.opcion = 1;

                Subcuenta = oSubCuentaRestClient.Save(Subcuenta);
                return AjaxResultSuccess("go");
            }
            catch (Exception ex)
            {
                ErrorSignal.FromCurrentContext().Raise(ex); //ELMAH Signaling
                return AjaxResultSuccess(ex.Message.Split('\"')[7].Split('\\')[0]);
            }
        }

        public ActionResult ActualizarUsuarios(decimal idUsuario)
        {
            /*open>>> Información: Código de identificación estándar */
            Decimal? Idns = 30010;
            /*close>> Información */

            try
            {
                var Model = new SubCuentasModels();

                var Subcuenta = new SubCuentaBE();
                Subcuenta = Model.SubCuenta;
                Subcuenta.nu_id_usuario = idUsuario;
                Subcuenta.vc_usr_mod = UsuarioSession.Usuario1.vc_cod_usuario;
                Subcuenta.opcion = 2;
                string fechacierre;
                fechacierre = DateTime.Now.ToShortDateString();
                Subcuenta.dt_fec_mod = Convert.ToDateTime(fechacierre);

                Subcuenta = oSubCuentaRestClient.Save(Subcuenta);

                /*Retornado la vista con el modelo seteado*/
                return AjaxResultSuccess("go");
            }


            catch (Exception ex)
            {
                ErrorSignal.FromCurrentContext().Raise(ex); //ELMAH Signaling
                return AjaxResultSuccess(ex.Message.Split('\"')[7].Split('\\')[0]);
            }
        }
    }
}

Siscom/Siscom/Areas/Global/Views/SubCuentas/Bandeja.cshtml
@using Siscom.Models

@model Siscom.Areas.Global.Models.SubCuentasModels

@{
    ViewBag.Title = "Bandeja";
    Layout = "~/Views/Home/Principal.cshtml";
}

<div class="pageheader">
    <!--Region Cabecera de la Pagina-->
    <h1>Bandeja de usuarios</h1>
    <div>
        <span class="label" style="color:rgb(144, 157, 163);padding:0px">USTED ESTÁ AQUÍ: </span>
        <ol class="breadcrumb">
            <li>
                <a href="#">Usuario</a>
            </li>
            <li>
                <a href="../../Global/SubCuentas/Bandeja" class="active">Bandeja</a>
            </li>
        </ol>
    </div>
</div>

<section id="main-content" class="animated fadeInUp">
<!--Region Botones-->
    <div class="row">
        <div class="col-xs-12">
           <div class="panel panel-default">                          
                <div class="panel-body text-left">
                    <button id="buscarBtn" type="button" class="btn btn-search btn-sm"
                        onclick="Buscar();">
                        <i class="fa fa-search"></i> Buscar
                    </button>  
                    <button id="agregarBtn" type="button" class="btn btn-primary btn-sm" 
                        onclick="Create('@Url.Action("Index", "SubCuentas")');">
                        <i class="fa fa-plus"></i> Nuevo usuario
                    </button>                      
                </div>
            </div>
        </div>
    </div>

<div id="DatosForm">
  
</div>
 <!--Lista de Usuarios-->
    <div class="row">
        <div class="col-md-12">
            <div class="panel panel-default">
                <div class="panel-body data-toggle="collapse">
                    <div id="div_ListaSolicitudes" class="table-responsive" style="padding-top:1px">
                     @Html.Partial("VP_GrillaSubCuentas", Model)
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

<!--Modal para mensajes-->
<div class="modal fade" id="ModalSave" style="overflow: scroll;" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h3 class="modal-title" id="myModalLabel" style="color:#0D588E">Mensaje de busqueda de usuarios</h3>
            </div>
            <div class="modal-body" id="SaveMensaje">
            </div>
            <div class="text-center">
                <hr /><button id="btnMensaje" type="button" class="btn btn-primary" onclick="$('#ModalSave').modal('hide');">Aceptar</button>
            </div>
        </div>
    </div>
</div>
<!--FIN-->

@section Styles {
@Styles.Render("~/plugins/dataTablesCSS")
}

<!--Load these page level functions-->
@section Scripts {
    @Scripts.Render("~/plugins/dataTables")
    @Scripts.Render("~/plugins/dataTables-bootstrap")
    @Scripts.Render("~/plugins/maskedinput")


    <script type="text/javascript" src="~/Scripts/plugins/datetimepicker/bootstrap-datetimepicker.js" charset="UTF-8"></script>
    <script type="text/javascript" src="~/Scripts/plugins/datetimepicker/locales/bootstrap-datetimepicker.es.js" charset="UTF-8"></script>
    <link href="~/Content/bootstrap-datetimepicker.min.css" rel="stylesheet" />

    <script type="text/javascript" src="~/Scripts/plugins/blockUI/js/jquery.blockUI.js" charset="UTF-8"></script>
    <script src="~/Scripts/jquery.number.js"></script>
    <script src="~/Scripts/jquery.number.min.js"></script>

<script type="text/javascript">  
    $(document).ready(function () {
        $('#DetalleSolicitudTable').dataTable({
            "order": [[3, "desc"]]
        });
        Buscar()
    });

    function Create(url) {
        window.location.href = url;
    }
   
    function Buscar() {
        $("#SaveMensaje").html('<i class="fa  fa-refresh" style="color:green"></i> Buscando usuarios, espere un momento...');
        $("#ModalSave").modal('show');
        
        $.ajax({
            type: 'POST',
            url: '/Global/SubCuentas/Buscar',
            
            success: function (result) {
                $('#div_ListaSolicitudes').andSelf().unbind();
                $('#div_ListaSolicitudes').html(result);
                if (result.trim() == "") {
                    $("#SaveMensaje").html('<i class="fa fa-remove" style="color:darkred"></i> No se encontró datos.');
                    $("#ModalSave").modal('show');
                }
                $(document).ready(function () {
                    $('#DetalleSolicitudTable').dataTable({
                        "order": [[3, "desc"]]
                    });
                });
                $("#ModalSave").modal('hide');
            }
        });

    }
    /*Ver Usuarios*/
    function Select(IdSubCuenta) {
        window.location.href = GetControllerUrl("Select", "SubCuentas") + '?IdSubCuenta=' + IdSubCuenta ;
    }
    /*FIN*/

    /*Actualizacion de usuario*/
    function Actualizar(idUsuario) {
        var Model = {
            idUsuario: idUsuario
        }
        $.ajax({
            type: "POST",
            url: GetControllerUrl("ActualizarUsuarios", "SubCuentas"),
            data: Model,
            success: function (resultado) {
                if (resultado.message == "go") {
                    Buscar();
                }
                else {
                    $("#guardarBtn").removeAttr('disabled');
                    $("#SaveMensaje").html('<i class="fa  fa-remove" style="color:darkred"></i> No se completo la actualización de la subcuenta: <br><strong>' + resultado.message + '</strong>');
                }
            }
        });
    }
</script>
}

Siscom/Siscom/Areas/Global/Views/SubCuentas/VP_GrillaSubCuentas.cshtml
@model Siscom.Areas.Global.Models.SubCuentasModels


 <table id="DetalleSolicitudTable" class="table table-striped table-bordered table-hover table-condensed " cellspacing="0">
    <thead>
        <tr>
            <th class="text-center" style="vertical-align:middle"><p>ESTADO</p></th>
            <th class="text-center" hidden="hidden"><p>ID_CUENTA</p></th>
            <th class="text-center" hidden="hidden"><p>ID_CONTACTO</p></th>
            <th class="text-center" style="vertical-align:middle"><p>CUENTA</p></th>
            <th class="text-center" style="vertical-align:middle"><p>ALIAS DEL USUARIO</p></th>
            <th class="text-center" style="vertical-align:middle"><p>D.N.I. CONTACTO</p></th>
            <th class="text-center" style="vertical-align:middle"><p>NOMBRE Y APELLIDO / CONTACTO</p></th>
            <th class="text-center" style="vertical-align:middle"><p>ACCIÓN</p></th>
        </tr>
    </thead>

    
 <tbody id="itemsDetalle">
@if (Model.ListaSubCuenta != null)
{
        foreach (var item in Model.ListaSubCuenta)
        { 
            <tr>
                <td class="text-center" style="font-weight:100;vertical-align:middle">
                @if(item.ch_status == "A")
                {
                    <button type="button" class="btn btn-primary" onclick="Actualizar(@item.nu_id_contacto);">
                        <h2 style="color:white">A</h2>
                    </button>
                }
                
                @if(item.ch_status == "I")
                {
                    <button type="button" class="btn btn-danger" onclick="Actualizar(@item.nu_id_contacto);">
                        <h2 style="color:white">I</h2>
                    </button>
                }</td>

                <td hidden="hidden"><p>@(item.nu_id_cuenta)</p></td>
                <td class="text-center" hidden="hidden"><p>@(item.nu_id_contacto)</p></td>
                <td class="text-center" style="vertical-align:middle"><p>@(item.vc_desc_cuenta)</p></td>
                <td class="text-center" style="vertical-align:middle"><p>@(item.vc_desc_sub_cuenta)</p></td>
                <td class="text-center" style="vertical-align:middle"><p>@(item.vc_doc_identi)</p></td>
                <td class="text-center" style="vertical-align:middle"><p>@(item.vc_nombres+' '+item.vc_apellidos)</p></td>
                <td class="text-center" style="vertical-align:middle"><button id="Ver" type="button" class="btn btn-info" onclick="Select(@item.nu_id_subcuenta);">
                    <i class="fa fa-search"></i>
                </button>
                </td>
            </tr>
        }
}                                        
    </tbody>
 </table>
      
    